on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      version_extractor:
        required: true
        type: string

jobs:
  bootstrap-binary:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v6
      - run: cargo build --release
      - uses: actions/upload-artifact@v6
        with:
          name: omnipackage-binary
          path: target/release/omnipackage
          retention-days: 1

  list-distros:
    needs: bootstrap-binary
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.get-distros.outputs.distros }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: omnipackage-binary
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/omnipackage
      - uses: actions/checkout@v6
      - id: get-distros
        run: echo "distros=$(omnipackage info --list-distros . --format json)" >> "$GITHUB_OUTPUT"

  release:
    needs: [bootstrap-binary, list-distros]
    runs-on: ubuntu-latest
    concurrency:
      group: omnipackage-${{ inputs.repository }}-${{ matrix.distro }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.list-distros.outputs.distros) }}
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get update -qq && sudo apt-get install -y -qq podman gpg
      - uses: actions/download-artifact@v8
        with:
          name: omnipackage-binary
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/omnipackage
      - run: echo "${{ secrets.OMNIPACKAGE_DOTENV }}" > .env
      - run:  omnipackage release . --build-dir $RUNNER_TEMP/_omp --repository "${{ inputs.repository }}" --distros "${{ matrix.distro }}" --version-extractor "${{ inputs.version_extractor }}"
