name: Image cache refresh

on:
  workflow_dispatch:
    inputs:
      image_cache:
        required: true
        type: string
        default: github

permissions:
  packages: write

jobs:
  bootstrap-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v6
      - run: cargo build --release
      - uses: actions/upload-artifact@v6
        with:
          name: omnipackage-binary
          path: target/release/omnipackage
          retention-days: 1

  list-distros:
    needs: bootstrap-binary
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.get-distros.outputs.distros }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: omnipackage-binary
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/omnipackage
      - uses: actions/checkout@v6
      - id: get-distros
        run: echo "distros=$(omnipackage info --list-distros . --format json)" >> "$GITHUB_OUTPUT"

  image_cache:
    needs: [bootstrap-binary, list-distros]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.list-distros.outputs.distros) }}
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get update -qq && sudo apt-get install -y -qq podman gpg
      - uses: actions/download-artifact@v8
        with:
          name: omnipackage-binary
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/omnipackage
      - run: |
          echo "${{ secrets.OMNIPACKAGE_DOTENV }}" > .env
          echo "GITHUB_REGISTRY_USERNAME=${{ github.actor }}" >> .env
          echo "GITHUB_REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> .env
          echo "GITHUB_REGISTRY_NAMESPACE=${{ github.repository_owner }}" >> .env
      - run:  omnipackage prime . --image-cache "${{ inputs.image_cache }}" --distros "${{ matrix.distro }}"
