name: Release packages - master

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [master]

jobs:
  bootstrap-binary:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v6

      - run: cargo build --release

      - uses: actions/upload-artifact@v6
        with:
          name: omnipackage-binary
          path: target/release/omnipackage
          retention-days: 1

  list-distros:
    needs: bootstrap-binary
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.get-distros.outputs.distros }}
    steps:
      - name: Download binary
        uses: actions/download-artifact@v8
        with:
          name: omnipackage-binary
          path: /usr/local/bin

      - run: chmod +x /usr/local/bin/omnipackage

      - uses: actions/checkout@v6

      - name: Get distro list
        id: get-distros
        run: echo "distros=$(omnipackage info --list-distros . --format json)" >> "$GITHUB_OUTPUT"

  release:
    needs: [bootstrap-binary, list-distros]
    runs-on: ubuntu-latest
    concurrency:
      group: omnipackage-master-${{ matrix.distro }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.list-distros.outputs.distros) }}
    env:
      REPOSITORY_NAME: "Cloudflare R2 master"
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y -qq podman gpg

      - name: Download binary
        uses: actions/download-artifact@v8
        with:
          name: omnipackage-binary
          path: /usr/local/bin

      - run: chmod +x /usr/local/bin/omnipackage

      - run: echo "${{ secrets.OMNIPACKAGE_DOTENV }}" > .env

      - name: Release packages for ${{ matrix.distro }}
        run:  omnipackage release . --build-dir $RUNNER_TEMP/_omp --repository $REPOSITORY_NAME --distros "${{ matrix.distro }}"

      - name: Get install page URL for deployment
        id: install-page-url
        run: echo "url=$(omnipackage info . --repository $REPOSITORY_NAME --show-install-page-url)" >> "$GITHUB_OUTPUT"

      #- name: Upload logs
      #  if: always()
      #  uses: actions/upload-artifact@v6
      #  with:
      #    name: logs-${{ matrix.distro }}
      #    path: |
      #      ${{ runner.temp }}/_omp/**/build.log
      #      ${{ runner.temp }}/_omp/**/publish.log
    environment:
      name: master
      url: ${{ steps.install-page-url.outputs.url }}
