name: Release packages - master

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [master]

jobs:
  run:
    uses: ./.github/workflows/_release-packages.yml
    secrets: inherit
    with:
      repository: "master"
      version_extractor: "git"
