name: Self-release master

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [master]

jobs:
  run:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    concurrency:
      group: omnipackage-master
      cancel-in-progress: false

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq podman

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - uses: actions/checkout@v6

      - run: echo "${{ secrets.OMNIPACKAGE_DOTENV }}" > .env

      - name: Build binary
        run: |
          cargo build --release
          sudo install -m 755  /usr/local/bin/omnipackage
          cargo clean

      - name: Release packages
        run: omnipackage release . --container-output null --repository "Cloudflare R2 master"
